name: CD

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_call:

jobs:
  Build:
    uses: ./.github/workflows/ci.yml

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    concurrency:
      group: cd-production
    env:
      DESTINATION: production
    permissions:
      packages: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Start the SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      - name: Expose the GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Deploy the application
        shell: bash
        env:
          ${{ insert }}: ${{ secrets }}
          DOCKER_BUILDKIT: 1
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: bin/kamal deploy --destination=$DESTINATION

      - name: Release the Kamal lock, if needed
        shell: bash
        if: ${{ cancelled() || failure() }}
        run: bin/kamal lock release --destination=$DESTINATION

      - name: Clean up old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          keep-n-tagged: 5
          keep-n-untagged: 5
          delete-orphaned-images: true
